### ISSUE TITLE
Any chance this will be updated?

### ISSUE THREAD

**Issue by monob0t** [jldiaz/cookiecutter-mkdocs-notes#3]
Hello, I like this cookiecutter a lot.

Any chance you will update the library versions? Thanks!

**Comment by jldiaz** [comment]
Thanks for using it. I updated `requirements.txt` file to the latest versions of all packages. This caused some incompatibility issues on some plugins, so I modified also `mkdocs.yml` to make all work again.

The syntax of some markdown extensions (mainly `superfences`) changed a bit, so I updated `docs/instructions.md` to reflect that. I also included a new markdown extension `tabbed`, which is pretty useful.

So f01c8e2d8ead0368ecb960aa0d56d1fb4f4b0c1a closes it.
